driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: centos-6.5
  - name: centos-6.5-i386
  - name: centos-5.10
    run_list:
      - recipe[yum]
    attributes:
      yum:
        main:
          gpgcheck: false
  - name: centos-5.10-i386
    run_list:
      - recipe[yum]
    attributes:
      yum:
        main:
          gpgcheck: false

suites:
  - name: default
    run_list:
      - recipe[oracle-instantclient]
    attributes:
      oracle-instantclient:
        public-url: "http://10.0.2.2/~<%= ENV['USER'] %>/binaries/"

  - name: perl
    run_list:
      - recipe[build-essential]
      - recipe[oracle-instantclient::perl]
    attributes:
      oracle-instantclient:
        public-url: "http://10.0.2.2/~<%= ENV['USER'] %>/binaries/"

  - name: php
    run_list:
      - recipe[build-essential]
      - recipe[oracle-instantclient::php]
    attributes:
      oracle-instantclient:
        public-url: "http://10.0.2.2/~<%= ENV['USER'] %>/binaries/"

  - name: ruby
    run_list:
      - recipe[oracle-instantclient::ruby]
    attributes:
      oracle-instantclient:
        public-url: "http://10.0.2.2/~<%= ENV['USER'] %>/binaries/"

  - name: sdk
    run_list:
      - recipe[oracle-instantclient::sdk]
    attributes:
      oracle-instantclient:
        public-url: "http://10.0.2.2/~<%= ENV['USER'] %>/binaries/"

  - name: sqlplus
    run_list:
      - recipe[oracle-instantclient::sqlplus]
    attributes:
      oracle-instantclient:
        public-url: "http://10.0.2.2/~<%= ENV['USER'] %>/binaries/"
